language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - TRANSPORT=jackrabbit
  - TRANSPORT=doctrine_dbal
#  - TRANSPORT=midgard_sqlite
#  - TRANSPORT=midgard_mysql

before_script:
  - composer self-update
  - ./tests/travis_${TRANSPORT}.sh

script: phpunit -c tests/phpunit_${TRANSPORT}.xml.dist

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"

matrix:
  allow_failures:
#    - env: TRANSPORT=midgard_sqlite
#    - env: TRANSPORT=midgard_mysql
