language: php

php:
  - 5.3
  - 5.4

env:
  - TRANSPORT=jackrabbit
#  - TRANSPORT=doctrine-dbal
  - TRANSPORT=midgard_sqlite
  - TRANSPORT=midgard_mysql

before_script:
  - ./tests/travis_${TRANSPORT}.sh
  - php composer install --dev

script: phpunit -c tests/phpunit_${TRANSPORT}.xml.dist

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
