language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER="weak"
  matrix:
    - TRANSPORT=jackrabbit
    - TRANSPORT=doctrine_dbal

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TRANSPORT=doctrine_dbal COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: TRANSPORT=jackrabbit COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: TRANSPORT=doctrine_dbal SYMFONY_REQUIRE="2.3.*"
    - php: 7.4
      env: TRANSPORT=jackrabbit SYMFONY_REQUIRE="2.3.*"
    - php: 7.4
      env: TRANSPORT=doctrine_dbal SYMFONY_REQUIRE="3.4.*"
    - php: 7.4
      env: TRANSPORT=jackrabbit SYMFONY_REQUIRE="3.4.*"
    - php: 7.4
      env: TRANSPORT=doctrine_dbal SYMFONY_REQUIRE="4.4.*"
    - php: 7.4
      env: TRANSPORT=jackrabbit SYMFONY_REQUIRE="4.4.*"
    - php: 8.0
      env: TRANSPORT=doctrine_dbal SYMFONY_REQUIRE="5.0.*"
    - php: 8.0
      env: TRANSPORT=jackrabbit SYMFONY_REQUIRE="5.0.*"
    - php: 7.4
      env: TRANSPORT=doctrine_dbal SYMFONY_REQUIRE="4.4.*" PHPBENCH="yes"
    - php: 7.4
      env: TRANSPORT=jackrabbit SYMFONY_REQUIRE="4.4.*" PHPBENCH="yes"
    - php: 8.0
      env: TRANSPORT=doctrine_dbal STABILITY="dev"
    - php: 8.0
      env: TRANSPORT=jackrabbit STABILITY="dev"

before_install:
  - phpenv config-rm xdebug.ini || true
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if [ "$PHPBENCH" = "yes" ]; then composer require --no-update phpbench/phpbench=~0.16; fi;
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  # this also does the composer update
  - COMPOSER_MEMORY_LIMIT=-1 ./tests/travis_${TRANSPORT}.sh

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit -c tests/phpunit_${TRANSPORT}.xml.dist
  - if [ "$PHPBENCH" = "yes" ]; then php vendor/bin/phpbench run --report=all; fi;

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
