language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  matrix:
    - TRANSPORT=jackrabbit
    - TRANSPORT=doctrine_dbal

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TRANSPORT=jackrabbit COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: TRANSPORT=doctrine_dbal DEPENDENCIES="symfony/lts:^3" PHPBENCH="yes"
    - php: 7.2
      env: TRANSPORT=jackrabbit DEPENDENCIES="symfony/lts:^3" PHPBENCH="yes"
    - php: 7.2
      env: TRANSPORT=doctrine_dbal COVERAGE=true DEPENDENCIES="symfony/symfony:^4.0" PHPBENCH="yes"
    - php: 7.2
      env: TRANSPORT=jackrabbit COVERAGE=true DEPENDENCIES="symfony/symfony:^4.0" PHPBENCH="yes"
    - php: 7.2
      env: TRANSPORT=doctrine_dbal STABILITY="dev"
    - php: 7.2
      env: TRANSPORT=jackrabbit STABILITY="dev"

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
  - if [ "$PHPBENCH" = "yes" ]; then composer require --no-update phpbench/phpbench=~1.0@dev; fi;

install:
  # this also does the composer update
  - ./tests/travis_${TRANSPORT}.sh

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit -c tests/phpunit_${TRANSPORT}.xml.dist
  - if [ "$PHPBENCH" = "yes" ]; then php vendor/bin/phpbench run --report=all; fi;

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
